export const ENDPOINTS = {
  API_BASE_URL: 'https://api.speakbetter.hng.tech/v1/',
  API_AUTH_LOGIN: 'auth/login',
  API_INITIATE_SIGNUP: 'auth/signup',
  API_GET_PROFILE: 'user/profile',
  API_SEND_AUDIO: 'conversation/sendAudio',
  API_AUTH_GOOGLE: 'auth/google',
  API_AUTH_LINKEDIN: 'auth/linkedin',
  API_AUTH_POST_LINKEDIN: (params) => `auth/linkedin/callback${params}`,
  API_AUTH_POST_GOOGLE: (params) => `auth/google/${params}`,
  API_BASE_PAYSTACK_URL: 'https://api.paystack.co/',
  API_AUTH_FACEBOOK: 'auth/facebook',
  API_AUTH_POST_FACEBOOK: (params) => `auth/facebook/callback${params}`,
  API_PAYSTACK_URL: 'paystack',
  API_PREMIUM_PAY: 'paystack/create',
  API_PREMIUM_VERIFY: (email, txref) => `paystack/verify?email=${email}&txref=${txref}`,
  API_PREMIUM_CANCEL: 'stripe/cancel',
  API_AUTH_FORGOT_PASSWORD: 'auth/request-password-reset',
  API_STRIPE_PAY: 'stripe/checkout',
  API_FLUTTER_PAY: 'subscription/create-pay',
  API_STRIPE_VERIFY: 'stripe/verify',
  API_AUTH_RESET_PASSWORD: (token) => `auth/password-reset?token=${token}`,
  API_USER_SUBSCRIPTION: () => 'subscription',
  API_USER_PROFILE: (userId) => `user/profile/${userId}`,

  API_STATUS_URL: 'test',
};
